broker: test.mosquitto.org
# port: 1883
port: 8884

to_publish:
  - "ShedSense/server/initialise_lots"

to_subscribe: 
  - "ShedSense/node/frame"
  - "ShedSense/node/status"
  - "ShedSense/node/annotated_frame"
  - "ShedSense/node/filtered_frame"
  - "ShedSense/node/shutdown"
  - "ShedSense/pi_zero/frame"
  - "ShedSense/node/alert_upgrade"

# cert file path
ca_cert: 
certfile: 
keyfile: 

