broker: test.mosquitto.org
port: 8884

topic: "shedsense/node/frame"

ca_cert: C:\Users\tanji\OneDrive\Cambridge\2\Project\MQTT_certs\mosquitto.org.crt
certfile: C:\Users\tanji\OneDrive\Cambridge\2\Project\MQTT_certs\client.crt
keyfile: C:\Users\tanji\OneDrive\Cambridge\2\Project\MQTT_certs\client.key

# payload: {img, timestamp}
