broker: test.mosquitto.org
# port: 8884
port: 1883

to_publish: 
  - "ShedSense/node/frame"
  - "ShedSense/node/status"
  - "ShedSense/node/annotated_frame"
  - "ShedSense/node/filtered_frame"
  - "ShedSense/node/shutdown"

to_subscribe:
  - "ShedSense/server/initialise_lots"

ca_cert: /home/shedsense1/Desktop/certs/mosquitto.org.crt
cert_file: /home/shedsense1/Desktop/certs/client.crt
key: /home/shedsense1/Desktop/certs/client.key
# payload: {img, timestamp}

# publisher topics
# ShedSense/node/frame
# ShedSense/node/status
# ShedSense/node/alert 