broker: test.mosquitto.org
port: 8884

handler_topics: 
  shedsense/node/frame
  shedsense/node/status
  shedsense/node/alert  

ca_cert: /home/shedsense1/ShedSense/node/src/mqtt/certs/mosquitto.org.crt
cert_file: /home/shedsense1/ShedSense/node/src/mqtt/certs/client.crt
key: /home/shedsense1/ShedSense/node/src/mqtt/certs/client.key
# payload: {img, timestamp}

# publisher topics
# ShedSense/node/frame
# ShedSense/node/status
# ShedSense/node/alert 