broker: test.mosquitto.org
port: 8884
# port: 1883

to_publish: 
  - "ShedSense/node/frame"
  - "ShedSense/node/status"
  - "ShedSense/node/annotated_frame"
  - "ShedSense/node/filtered_frame"
  - "ShedSense/node/shutdown"

to_subscribe:
  - "ShedSense/server/initialise_lots"
  - "ShedSense/pi_zero/frame"

# cert file path
ca_cert: 
cert_file: 
key: 

# publisher topics
# ShedSense/node/frame
# ShedSense/node/status
# ShedSense/node/alert 