broker: test.mosquitto.org
port: 8884
# port: 1883

to_publish: 
  - "ShedSense/pi_zero/frame"
  
to_subscribe:

# cert file path
ca_cert: 
cert_file: 
key: 

# publisher topics
# ShedSense/node/frame
# ShedSense/node/status
# ShedSense/node/alert 